bazel_dep(name = "rules_rust", version = "0.65.0")
rust = use_extension("@rules_rust//rust:extensions.bzl", "rust")
rust.toolchain(
    edition = "2021",
    versions = ["1.85.0"],
)
use_repo(rust, "rust_toolchains")
register_toolchains("@rust_toolchains//:all")
# crate = use_extension("@rules_rust//crate_universe:extensions.bzl", "crate")
# crate.spec(
#     package = "clap",
#     version = "4.5",
#     features = ["derive"],
# )
# crate.spec(
#     package = "serde",
#     version = "1.0",
#     features = ["derive"],
# )
# crate.spec(
#     package = "toml",
#     version = "0.8",
# )
# crate.spec(
#     package = "toml_edit",
#     version = "0.22",
# )
# crate.from_specs()
# use_repo(crate, "crates")
